export type BsEventBusType =
  | 'BS::SYNCHRO::SUCCESS'
  | 'BS::SYNCHRO::FAIL'
  | 'BS::PLAYERS::CHANGE'
  | 'BS::TEAMS::CHANGE'
  | 'BS::MATCHS::CHANGE'
  | 'BS::CONTACTS::CHANGE'
  | 'BS::THEME::CHANGE'
  | 'BS::TROMBI_TITLES::CHANGE'
