import { Mail, Pencil, Phone, Plus, Save, Trash, X } from 'lucide-solid'
import { createSignal, For, Show } from 'solid-js'
import Contact, { getRelationshipLabel, isContactRelationship, RELATIONSHIP_LABELS } from '../../libs/contact/contact'
import type { ContactRawData } from '../../libs/contact/contact.d'
import { toast } from '../../libs/utils/utils'
import BsInput from '../input/input'
import BsSelect from '../select/select'
import type { BsContactsEditorProps } from './contacts-editor.d'

/**
 * Draft row for a brand-new contact. The id is generated by the `Contact`
 * entity; the parent's `onAdd` binds the playerId of the current draft.
 */
function makeEmptyContact(): ContactRawData {
  return new Contact({ relationship: 'mother' }).getRawData()
}

function makeContactRelationshipChangeHandler(setNewContactData: (data: Partial<ContactRawData>) => void) {
  return (value: string) => {
    if (isContactRelationship(value)) {
      setNewContactData({ relationship: value })
    }
  }
}

function makeEditContactClickHandler(editContact: (contact: ContactRawData) => void, contact: ContactRawData) {
  return () => {
    editContact(contact)
  }
}

function makeDeleteContactClickHandler(deleteContact: (contact: ContactRawData) => void, contact: ContactRawData) {
  return () => {
    deleteContact(contact)
  }
}

export default function BsContactsEditor(props: BsContactsEditorProps) {
  const [isAddingContact, setIsAddingContact] = createSignal(false)
  const [isNewContact, setIsNewContact] = createSignal(false)
  const [contactDraft, setContactDraft] = createSignal<ContactRawData | null>(null)
  const editContactLabel = 'Modifier le contact'
  const deleteContactLabel = 'Supprimer le contact'

  /**
   * The staged contacts are a reactive store owned by the parent form, so the
   * list re-renders on every parent mutation (add/update/remove) without any
   * bus event or adapter.
   */
  function startNewContact() {
    setIsNewContact(true)
    setContactDraft(makeEmptyContact())
    setIsAddingContact(true)
  }

  function editContact(contact: ContactRawData) {
    setIsNewContact(false)
    setContactDraft({ ...contact })
    setIsAddingContact(true)
  }

  function cancelContactEdit() {
    setContactDraft(null)
    setIsAddingContact(false)
  }

  function setNewContactData(data: Partial<ContactRawData>) {
    setContactDraft((current) => (current ? { ...current, ...data } : current))
  }

  function registerContact() {
    const draft = contactDraft()
    if (!draft) {
      return
    }
    try {
      if (isNewContact()) {
        props.onAdd(draft)
      } else {
        props.onUpdate(draft)
      }
      setContactDraft(null)
      setIsAddingContact(false)
    } catch {
      toast("Erreur lors de l'enregistrement du contact.", 'error')
    }
  }

  function deleteContact(contact: ContactRawData) {
    try {
      props.onRemove(contact.id ?? '')
    } catch {
      toast('Erreur lors de la suppression du contact.', 'error')
    }
  }

  function renderContactEditForm() {
    const editedContact = contactDraft()

    return (
      <div class="flex flex-col gap-2 rounded-lg bg-base-200 p-3">
        {BsInput({
          label: 'Nom',
          onChange: (value: string) => {
            setNewContactData({ lastName: value })
          },
          placeholder: 'Dupont',
          type: 'text',
          value: editedContact?.lastName,
        })}
        {BsInput({
          label: 'Prénom',
          onChange: (value: string) => {
            setNewContactData({ firstName: value })
          },
          placeholder: 'Charlie',
          type: 'text',
          value: editedContact?.firstName,
        })}
        <BsSelect
          datas={[...RELATIONSHIP_LABELS]}
          label="Relation"
          onValueChange={makeContactRelationshipChangeHandler(setNewContactData)}
          value={editedContact?.relationship}
        />
        {BsInput({
          label: 'Téléphone',
          onChange: (value: string) => {
            setNewContactData({ phone: value })
          },
          placeholder: '06 12 34 56 78',
          type: 'text',
          value: editedContact?.phone,
        })}
        {BsInput({
          label: 'Email',
          onChange: (value: string) => {
            setNewContactData({ email: value })
          },
          placeholder: 'contact@example.com',
          type: 'email',
          value: editedContact?.email,
        })}
        {BsInput({
          label: 'Adresse',
          onChange: (value: string) => {
            setNewContactData({ address: value })
          },
          placeholder: '12 rue du Sport, 75001 Paris',
          type: 'text',
          value: editedContact?.address,
        })}
        <div class="footer-buttons-container">
          <button class="btn btn-primary btn-wide" onClick={cancelContactEdit} type="button">
            <X />
            Annuler
          </button>
          <button class="btn btn-primary btn-wide" onClick={registerContact} type="button">
            <Save />
            Enregistrer
          </button>
        </div>
      </div>
    )
  }

  return (
    <>
      <hr class="my-2" />
      <div class="flex flex-col gap-2">
        <div class="flex items-center justify-between">
          <h3 class="font-semibold text-lg">Contacts</h3>
          <Show when={!isAddingContact()}>
            <button class="btn btn-primary btn-sm" onClick={startNewContact} type="button">
              <Plus />
              Ajouter
            </button>
          </Show>
        </div>

        <Show when={isAddingContact()}>{renderContactEditForm()}</Show>

        <Show when={!isAddingContact()}>
          <Show
            fallback={<p class="italic opacity-70">Aucun contact enregistré pour ce joueur.</p>}
            when={props.contacts.length > 0}
          >
            <div class="flex flex-col gap-2">
              <For each={props.contacts}>
                {(contact) => (
                  <div class="flex items-center gap-2 rounded-lg bg-base-200 p-3">
                    <div class="flex flex-1 flex-col gap-1">
                      <span class="font-medium">
                        {contact.firstName} {contact.lastName}
                      </span>
                      <span class="text-sm opacity-70">{getRelationshipLabel(contact.relationship ?? 'other')}</span>
                      <Show when={contact.phone}>
                        <span class="flex items-center gap-1 text-sm">
                          <Phone class="size-4" />
                          {contact.phone}
                        </span>
                      </Show>
                      <Show when={contact.email}>
                        <span class="flex items-center gap-1 text-sm">
                          <Mail class="size-4" />
                          {contact.email}
                        </span>
                      </Show>
                    </div>
                    <div class="tooltip tooltip-top" data-tip={editContactLabel}>
                      <button
                        aria-label={editContactLabel}
                        class="btn btn-square btn-sm"
                        onClick={makeEditContactClickHandler(editContact, contact)}
                        type="button"
                      >
                        <Pencil />
                      </button>
                    </div>
                    <div class="tooltip tooltip-top" data-tip={deleteContactLabel}>
                      <button
                        aria-label={deleteContactLabel}
                        class="btn btn-square btn-sm"
                        onClick={makeDeleteContactClickHandler(deleteContact, contact)}
                        type="button"
                      >
                        <Trash />
                      </button>
                    </div>
                  </div>
                )}
              </For>
            </div>
          </Show>
        </Show>
      </div>
    </>
  )
}
