import { CloudDownload, CloudUpload, LoaderCircle, X } from 'lucide-solid'
import { createUniqueId, For, onMount, Show } from 'solid-js'
import type { NostromoRestoreDecision, NostromoRestorePlan } from '../../libs/nostromo/restore.d'
import { countNostromoPlanChanges, describeNostromoPlan } from './bs-nostromo-status'
import type { BsNostromoRestoreModalProps } from './bs-nostromo-sync.d'

/** Neutral title of the modal, for a plan that overwrites and deletes nothing: correct French plural. */
function neutralPlanTitle(plan: NostromoRestorePlan): string {
  const changes = countNostromoPlanChanges(plan)
  return `Vous allez appliquer ${changes} changement${changes > 1 ? 's' : ''} depuis le serveur.`
}

/**
 * Confirmation modal of a restore plan: the user reads what a pull would
 * overwrite (or delete) and answers with one of the three decisions of
 * `confirmNostromoRestore`.
 *
 * The plan warnings are generated by the sync layer and are French, like the
 * surrounding copy: they name units and server state verbatim.
 */
export default function BsNostromoRestoreModal(props: BsNostromoRestoreModalProps) {
  const titleId = createUniqueId()

  // biome-ignore lint/suspicious/noUnassignedVariables: assigned by SolidJS ref prop
  let dialogEl: HTMLDialogElement | undefined

  // The dialog is rendered open instead of shown with `showModal()`: it keeps the
  // markup testable, and the focus below is what makes Escape reach it.
  onMount(() => {
    dialogEl?.focus()
  })

  const decide = (decision: NostromoRestoreDecision) => () => props.onDecision(decision)

  function onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape' && !props.busy) {
      props.onDecision('cancel')
    }
  }

  return (
    /* biome-ignore lint/a11y/noNoninteractiveElementInteractions: <dialog> is a native interactive element, and the handler only answers Escape */
    <dialog aria-labelledby={titleId} class="modal modal-middle" onKeyDown={onKeyDown} open ref={dialogEl}>
      <div class="modal-box max-h-[calc(100dvh-4rem)] w-[calc(100%-2rem)] max-w-lg overflow-y-auto">
        <div class="flex items-start justify-between gap-2">
          <h3 class="flex items-center gap-2 font-bold text-lg" id={titleId}>
            <CloudDownload />
            Restaurer depuis Nostromo
          </h3>
          <button
            aria-label="Fermer"
            class="btn btn-square btn-sm"
            disabled={props.busy}
            onClick={decide('cancel')}
            type="button"
          >
            <X />
          </button>
        </div>

        {/* `requiresConfirmation` is the plan's destructive signal: it is only set
            when a pull overwrites local data or deletes a local photo. */}
        <Show
          fallback={<p class="mt-4 font-medium">{neutralPlanTitle(props.plan)}</p>}
          when={props.plan.requiresConfirmation}
        >
          <p class="mt-4 font-medium text-warning">Vous allez écraser des données plus récentes.</p>
        </Show>
        <p class="mt-1 text-base-content/70 text-sm">{describeNostromoPlan(props.plan)}</p>
        <Show when={props.host}>{(host) => <p class="mt-1 text-base-content/70 text-sm">Source : {host()}.</p>}</Show>

        <Show when={props.plan.warnings.length > 0}>
          <ul class="mt-2 max-h-64 list-disc space-y-1 overflow-y-auto pl-4 text-sm">
            <For each={props.plan.warnings}>{(warning) => <li class="break-words">{warning}</li>}</For>
          </ul>
        </Show>

        <dl class="mt-4 space-y-1 text-sm">
          <div>
            <dt class="font-medium">Restaurer le serveur</dt>
            <dd class="text-base-content/70">Reprend les données du serveur sur cet appareil.</dd>
          </div>
          <div>
            <dt class="font-medium">Écraser le serveur</dt>
            <dd class="text-base-content/70">Envoie les données locales sur le serveur.</dd>
          </div>
        </dl>

        <Show when={props.busy}>
          <p class="mt-3 flex items-center gap-2 text-sm">
            <LoaderCircle class="animate-spin" size={16} />
            Traitement en cours…
          </p>
        </Show>

        <div class="modal-action flex-wrap">
          <button class="btn btn-ghost" disabled={props.busy} onClick={decide('cancel')} type="button">
            Annuler
          </button>
          <button class="btn btn-warning" disabled={props.busy} onClick={decide('pull')} type="button">
            <CloudDownload />
            Restaurer le serveur
          </button>
          <button class="btn btn-error" disabled={props.busy} onClick={decide('overwrite')} type="button">
            <CloudUpload />
            Écraser le serveur
          </button>
        </div>
      </div>
    </dialog>
  )
}
