export type DaisyVariant =
  | 'text'
  | 'primary'
  | 'primary-content'
  | 'secondary'
  | 'secondary-content'
  | 'accent'
  | 'accent-content'
  | 'neutral'
  | 'neutral-content'
  | 'success'
  | 'success-content'
  | 'warning'
  | 'warning-content'
  | 'error'
  | 'error-content'

export type DaisySize = 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl' | '3xl'

export type DaisyAlert = 'info' | 'success' | 'warning' | 'error'
